### ISSUE TITLE
Leaking golang http user agent

### ISSUE THREAD

**Issue by ioerror** [janimo/textsecure#12]
I noticed that the code reveals the default Go http user agent:
```
Host: textsecure-service.whispersystems.org:443
User-Agent: Go 1.1 package http
```

I propose:
```
User-Agent: Signal
```
```
diff --git a/transport.go b/transport.go
index 76d974f..ccb6ede 100644
--- a/transport.go
+++ b/transport.go
@@ -63,6 +63,7 @@ func newHTTPTransporter(baseURL, user, pass string, skipTLSCheck bool) *httpTran
 func (ht *httpTransporter) get(url string) (*response, error) {
        req, err := http.NewRequest("GET", ht.baseURL+url, nil)
        req.SetBasicAuth(ht.user, ht.pass)
+       req.Header.Add("User-Agent", "Signal")
        resp, err := ht.client.Do(req)
        r := &response{}
        if resp != nil {
@@ -81,6 +82,7 @@ func (ht *httpTransporter) put(url string, body []byte, ct string) (*response, e
        br := bytes.NewReader(body)
        req, err := http.NewRequest("PUT", ht.baseURL+url, br)
        req.Header.Add("Content-type", ct)
+       req.Header.Add("User-Agent", "Signal")
        req.SetBasicAuth(ht.user, ht.pass)
        resp, err := ht.client.Do(req)
        r := &response{}
```

This doesn't fixup the header for the CONNNECT proxy code.

**Comment by janimo** [comment]
I agree it would be better not to leak client info.
The leak is to the whisper server only ( in theory ).
I haven't checked the other clients (iOS Signal, Android TextSecure, Chrome extension) but they presumably each identify themselves differently.
If the purpose of this change is to identify as one of the existing clients, I think other headers should be made to match no? And even so the timing of the requests would probably identify this the the Go client.

**Comment by ioerror** [comment]
I think it is dangerous to uniquely identify each client - for example - how is your cert pinning code?

**Comment by janimo** [comment]
There's no cert pinning code, I just filed an issue earlier today. How is that related to client identification?
BTW, there's a textsecure-go mailing list (almost no traffic though) in case you think some of the discussions are better suited to email format than here.
https://groups.google.com/forum/#!forum/textsecure-go

**Comment by ioerror** [comment]
As an example, if there isn't cert pinning code and there is a vuln, fingeprinting may ensure that only vulnerable users are targeted.

**Comment by janimo** [comment]
There's now cert pinning, as done by the Android client (use a hardcoded certificate instead of the host's CA list)
