### ISSUE TITLE
Use certificate pinning like the Android client does

### ISSUE THREAD

**Issue by janimo** [janimo/textsecure#13]
In order to be safer against MITM attacks, check we are connecting to the right server.

**Comment by f41c0r** [comment]
We can't just hardcode (or add an option to specify an overriding) sha fingerprint of the server's cert into the library and then just perform a check on connect?

**Comment by janimo** [comment]
Yes,I think that is the way to do it, hardcoding (plus config override) of the server certificate's public key's hash. zaki's fork of this lib has some code for that, I just wanted to first check out what the Android client does exactly and replicate that.

**Comment by janimo** [comment]
Did it by setting the server's certificate to be the root CA instead of the host's default CA list.
