### ISSUE TITLE
Provide API to shut down message listener

### ISSUE THREAD

**Issue by abarisani** [janimo/textsecure#16]
Hello,

as an improvement to the API it would be nice to have a counterpart to the ListenForMessages() function that allows to stop listening for messages. Currently I see no way of doing that.

Thanks

**Comment by janimo** [comment]
Would just ignoring messages when the application no longer wants them not be enough?
Do you need this to make sure the messages are still on the server to be received later on?

**Comment by abarisani** [comment]
Yes, I'd like to be able to shut the listener down entirely so that messages are not ack'ed by the server. Basically I need to close the entire goroutine, I suggest allocating a channel for doing so.

**Comment by janimo** [comment]
5803d7f adds Start/StopListening() via an API break. There were many different ways this could have been done, let me know if this is ok for you.
We could just keep receiving but not ack, or stop receiving but keep the connection alive, or stop the connection altogether and require reconnection if messages are to be received again (picked this one).

**Comment by abarisani** [comment]
I agree with the option that you picked, I think it is better to not do anything under the hood if the user wants to stop listening for messages. Thanks!
