### ISSUE TITLE
After registration, sending/receiving messages fails on phone

### ISSUE THREAD

**Issue by elimisteve** [janimo/textsecure#18]
It seems that my phone has been deregistered as a result of registering with my phone number from the `textsecure` command line program.

How do I fix this so I can send and receive TextSecure messages on my phone again?  Thanks!

**Comment by elimisteve** [comment]
I suppose I need to re-register from my phone somehow, but I'm not sure how to do this without deleting the app + convos + keys, which I really really don't want to do.

**Comment by janimo** [comment]
I think re-registering on the phone (disabling and then re-enabling the TextSecure data toggle in settings) will cause your keys to be replaced. I don't remember about convos.
If that is an issue I suggest using another number for expermenting with this tool. I plan to support the device sysncing mechanism after it lands upstream (Android + Chrome app) and that will allow using the cli to complement the Android app.

**Comment by elimisteve** [comment]
Solved: https://github.com/janimo/textsecure/issues/4
