### ISSUE TITLE
Interoperation with Signal

### ISSUE THREAD

**Issue by abarisani** [janimo/textsecure#21]
Hello,

using the library interaction with Android version of TextSecure works flawlessly, however when communicating with Signal on iPhones sent messages are received corrupted (error message: "Received message was corrupted").

Messages sent from Signal to the library works fine.

This has been tested with Signal 2.1.3 on an iPhone 5s.

**Comment by janimo** [comment]
Hi, can you check if this is a regression due to the next to last commit?

**Comment by abarisani** [comment]
Yes, I can confirm that the next to last commit introduced the issue.
