### ISSUE TITLE
can't send attachment to group chat

### ISSUE THREAD

**Issue by morph027** [janimo/textsecure#22]
I just tried to setup a group and send images to it (this works in android client, so the protocol should support it ;) ). I can send text messages but no attachments, it always returns a 404.

```
./textsecure -group=true -to=${HEX-ID} -message=Test -attachment="/tmp/test.jpg"
status code 404
```

**Comment by janimo** [comment]
thanks for the report.
can you retry with current master?

**Comment by morph027** [comment]
Jip, works perfectly, thanks! ;)
