### ISSUE TITLE
push service error

### ISSUE THREAD

**Issue by amatanat** [janimo/textsecure#23]
Hello,

I am trying to run my own signal-android. When android device in connected to the server, after code verification it generate keys but gives error in registering with server as 'was unable to connect to push service'. How can I solve this problem?

**Comment by janimo** [comment]
Hello,
I am not sure how this is related to the Go textsecure package. Can you clarify?

**Comment by amatanat** [comment]
I am not sure maybe it is not the correct package to ask this question. Maybe it is related to WhisperSystems/TextSecure-Server package.

**Comment by janimo** [comment]
If you are not using this package (which is a client library written in Go, and has nothing to do with the Android client) then the issue to report is against Android-Signal. But if you built your own Android client you'll need your own REGISTRATION_ID registered with google and change it in
src/org/thoughtcrime/securesms/jobs/GcmRefreshJob.java
There's documentation on the internet about how to set up your apps GCM ID for push to work.
