### ISSUE TITLE
avoid "vendor" path to play nicely with upcoming vendoring default

### ISSUE THREAD

**Issue by abarisani** [janimo/textsecure#24]
Go 1.6 keeps the vendoring support, no longer considered experimental, and enables it by default.

To anticipate its release (now in Beta) it would be nice not to collide with the "vendor" path (https://github.com/golang/go/issues/12111) as with GO15VENDOREXPERIMENT currently the issue is raised:

```
$ export GO15VENDOREXPERIMENT=1
$ go get -u -tags textsecure github.com/inversepath/interlock/cmd/interlock
package github.com/inversepath/interlock/cmd/interlock
	imports github.com/janimo/textsecure
	imports github.com/janimo/textsecure/vendor/magic: must be imported as magic
```

Thanks!

**Comment by janimo** [comment]
Thanks, I was planning on trying a build with 1.5 or later and reorg our vendor code. Will do before 1.6 releases, I promise :)

**Comment by janimo** [comment]
Fixed in the latest commit.
