### ISSUE TITLE
video attachments won't work 

### ISSUE THREAD

**Issue by malfino** [janimo/textsecure#29]
setup: fresh install of textsecure-cmd from today's master and fresh install of the signal app on my nexus 6 with cm13  version 3.16.0

new key-handshake and everything.

If i send a jpg attachment to my phone then it's totally fine.
But if I send a video, the phone says, that a media message has been received, but when I go in the signal  app, there is only a strange speech bubble with only the lock and the time. I tested different video formats, 3gp, avi, mp4. None of these work. FWIW, I have enabled the video download via mobile data, wifi and roaming. 

Could you check, what the problem with sending videos might be?

**Comment by janimo** [comment]
Hmm, I just checked now, and it worked with fine the first video sent (ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]). There's no thumbnail shown in the Android app but it plays fine.

**Comment by malfino** [comment]
Can you upload your video file somewhere, so I can check if it's my setup or my video files, that cause the problem?

**Comment by janimo** [comment]
I've found a video that does not go over, I'll look into it.

**Comment by janimo** [comment]
Can you retry with the latest code? Thanks.

**Comment by malfino** [comment]
Whatever you did, it worked. It now works great again.Thanks a lot. Please close this issue.

**Comment by janimo** [comment]
I did a long overdue change to use another mimetype detection library. The previous one did not detect most video and sound files correctly. Thanks for raising the issue.
