### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by abarisani** [janimo/textsecure#33]
Hello,

I am currently experiencing the following:

panic: runtime error: slice bounds out of range

goroutine 194 [running]:
github.com/janimo/textsecure.handleReceivedMessage(0x0, 0x0, 0x0, 0x555880, 0x10a78040)
        .../go/src/github.com/janimo/textsecure/textsecure.go:462 +0xa2c
github.com/janimo/textsecure.StartListening(0x590c68, 0x5)
        .../go/src/github.com/janimo/textsecure/websocket.go:204 +0x1e0

Could this be handled cleanly? Also I am not sure what's the cause at the moment, could be connectivity issues but I'm not sure.

**Comment by janimo** [comment]
Hi,
it's probably the same as
https://github.com/janimo/textsecure-qml/issues/47

I'll have to try the code against new version of the server and maybe newer clients. I'd guess new types of messages have been added which the old code does not handle well?

**Comment by abarisani** [comment]
I applied the workaround listed in https://github.com/janimo/textsecure-qml/issues/47#issuecomment-297052076 and I confirm that an empty message was received (I debugged the function byte array argument and it was empty).

Can the fix be applied?

Thanks!

**Comment by janimo** [comment]
Please file a PR, and I'll apply it, thanks :)
