### ISSUE TITLE
Recieving messages

### ISSUE THREAD

**Issue by onny** [janimo/textsecure#4]
Hey,
your implementation looks really interesting and I'm looking forward to use this as a library.
I could successfully sent a message to a friend using your command line tool!

I would like to use something like "-l" for listening to incoming messages?

Thank you!

**Comment by elimisteve** [comment]
@onny Did you do anything special to re-register your phone so you could send and receive TextSecure messages again?  Once I registered with the `textsecure` command line program, I was unable to send and receive texts on my phone.  Thank you!

**Comment by janimo** [comment]
You need to reregister indeed or use another number for playing with textsecure (a free wilio one for example)

**Comment by elimisteve** [comment]
@janimo Is the only way to reregister on the phone by uninstalling and reinstalling?  (Right now I'm looking into how to back up my private key and not just my texts, thanks.)

**Comment by janimo** [comment]
In android there's a toggle in settings/advanced.

**Comment by janimo** [comment]
you could also google to see how others deal with backup/resinstalls, I did not need this so I cannot help.

**Comment by elimisteve** [comment]
@janimo Top-right drop-down > Advanced > Disabling "TextSecure messages" (which warns of the de-registration), then going back and re-enabling "TextSecure messages" indeed did the trick!  Thanks!

**Comment by elimisteve** [comment]
@janimo In the future, hopefully it'll be possible to be "logged in" as the same user/phone numbers on multiple devices at the same time, so I can basically use `textsecure` as a chat client.  Do you know if this is supported by the protocol?
