### ISSUE TITLE
Support group chats

### ISSUE THREAD

**Issue by onny** [janimo/textsecure#5]

**Comment by janimo** [comment]
Master now supports sending and receiving group messages. Group creation/update/leaving is not done yet.

**Comment by zmanian** [comment]
So excited to merge this.

**Comment by onny** [comment]
This sounds awesome, thank you for your work, I'll test it!

**Comment by janimo** [comment]
creating and leaving groups is also supported.

**Comment by janimo** [comment]
UpdateGroup API added.
